name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/routing-server:latest

      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.KEY }}
      #     port: 22
      #     script: docker stop server && docker pull am271/routing-server:v1.1 && docker run -dt --rm --name server -p 5566:5566 am271/routing-server:v1.1